### ISSUE TITLE
Hat is parented inside of random parts

### ISSUE THREAD

**Issue by DefaultTool** [presssssure/team-create-hats#18] opened 2021-10-24 05:28 UTC
Hat is parented inside of random parts and classes and cannot be moved.

**Comment by Milo123459** [comment] 2022-02-19 16:10
@presssssure This is also happening to me. It is being put in `Terrain` for me.

**Comment by presssssure** [comment] 2022-02-25 02:46
I still haven't been able to replicate the original issue, but putting hats in Terrain is intentional @Milo123459. Otherwise they'd be highlighted when someone clicked on workspace, and usually plugins use Terrain as a folder for things that don't need to be seen in the explorer but need to exist in the workspace.

**Comment by prepsure** [comment] 2024-12-23 06:11
Closing this because reproduction steps haven't been provided.

**Closed as completed by prepsure** 2024-12-23 06:11 UTC
